name: Update Trailhead Stats
on:
  schedule:
    - cron: '0 * * * *' # Runs hourly
jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: nabondance/trailhead-stats@v2.0.0
        with:
          trailhead-username: 'https://www.salesforce.com/trailblazer/jross'
          display-type: 'card'
          show-certification: 'detail'
